apiVersion: v1
kind: Service
metadata:
  name: blue-green-demo-service
  labels:
    app: blue-green-demo
spec:
  selector:
    app: blue-green-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
